### GET request to example server
POST http://localhost:4004/api/patient/createPatient
Content-Type: application/json

{
  "name": "John Doe with Billing account",
  "email": "test_billing_account_kafka91311@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}
###